[build]
  # Directory to change to before starting build
  base = "/"


  command = "CI=false npm run build"
  publish = "/opt/build/repo/build/static"


# This is a redirect rule to handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


